# Test your FastAPI endpoints

### Valid data, (criterion = completed)
POST http://127.0.0.1:8000/solution
Content-Type: application/json

{
    "orders": [
       {"id": 1, "item": "Laptop", "quantity": 1, "price": 999.99, "status": "completed"},
       {"id": 2, "item": "Smartphone", "quantity": 2, "price": 499.95, "status": "pending"},
       {"id": 3, "item": "Headphones", "quantity": 3, "price": 99.90, "status": "completed"},
       {"id": 4, "item": "Mouse", "quantity": 4, "price": 24.99, "status": "canceled"}
    ],
   "criterion": "completed"
}

### Valid data, (criterion = all)
POST http://127.0.0.1:8000/solution
Content-Type: application/json

{
    "orders": [
       {"id": 1, "item": "Laptop", "quantity": 1, "price": 999.99, "status": "completed"},
       {"id": 2, "item": "Smartphone", "quantity": 2, "price": 499.95, "status": "pending"},
       {"id": 3, "item": "Headphones", "quantity": 3, "price": 99.90, "status": "completed"},
       {"id": 4, "item": "Mouse", "quantity": 4, "price": 24.99, "status": "canceled"}
    ],
   "criterion": "all"
}

### Invalid data, (negative numbers prices, quantity)
POST http://127.0.0.1:8000/solution
Content-Type: application/json

{
   "orders": [
       {"id": 1, "item": "Laptop", "quantity": -5, "price": 999.99, "status": "completed"},
       {"id": 2, "item": "Smartphone", "quantity": 2, "price": -499.95, "status": "pending"}
   ],
   "criterion": "completed"
}

### Invalid data, (invalid criterion and status)
POST http://127.0.0.1:8000/solution
Content-Type: application/json

{
   "orders": [
       {"id": 1, "item": "Laptop", "quantity": 5, "price": 999.99, "status": "invalid_status"}
   ],
   "criterion": "invalid_criterion"
}